[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  external_node_modules = ["nodemailer"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
